# prefix + r: reload config
unbind r
bind r source-file ~/.tmux.conf

set-option -g default-terminal "tmux-256color"
set-option -sa terminal-features ",$TERM:RGB"

# allows shift-click on hyperlinks
set-option -sa terminal-features ",$TERM:hyperlinks"

set-option -g focus-events on

set -g mouse on
set -g prefix C-Space
bind C-Space send-prefix

set -g mode-keys vi
set -g status-keys vi
set -g escape-time 25
set -g cursor-colour white

set -g status-position top

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -g allow-rename off

# remap splits to open pane in cwd
bind h split-window -v -c "#{pane_current_path}"
bind v split-window -h -c  "#{pane_current_path}"

# cloned manually to ~/.tmux/plugins/tpm/
# prefix + I: install other plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# enter vi mode: prefix + [
# enter select mode: <space>
# switch in/out visual line mode: v
# copy to selection to clipboard: y
set -g @plugin 'tmux-plugins/tmux-yank'

# move between vim/tmux with: Ctrl+(h|j|k|l)
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-boot 'on'
set -g @continuum-boot-options 'alacritty'
set -g @continuum-restore 'on'

# highlight text in select mode, then press 'x' to open
set -g @plugin 'tmux-plugins/tmux-open'
set -g @open 'x'

# theme
# check migration guide if stuff isn't working https://github.com/catppuccin/tmux/issues/487
set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @catppuccin_flavour 'mocha'

set -g @catppuccin_window_status "icon"
set -g @catppuccin_window_status_style "basic"

set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

set -g @catppuccin_window_flags "icon"
set -g @catppuccin_window_flags_icon_zoom " 󰛭"
set -g @catppuccin_window_flags_icon_last " 󱞱"
set -g @catppuccin_window_flags_icon_current ""

run '~/.tmux/plugins/tmux/catppuccin.tmux'

set -g status-right-length 100
set -g status-left-length 100
set -g status-left "◿ "
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

# should be final line
run '~/.tmux/plugins/tpm/tpm'

